spring:
  application:
    name: refis-application-discovery
server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    #for production config is recommended use another instance, set true to this property
    fetch-registry: false
